import type { Agent, TicketCategory, Ticket, KBArticle, TicketCluster, AgentAnalytics } from '../types';

export const mockAgents: Agent[] = [
  {
    id: '1',
    email: 'admin@support.com',
    fullName: 'Sarah Admin',
    role: 'admin',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: '2',
    email: 'john@support.com',
    fullName: 'John Senior',
    role: 'senior_agent',
    isActive: true,
    createdAt: '2024-01-15T00:00:00Z',
    lastActiveAt: new Date().toISOString(),
  },
  {
    id: '3',
    email: 'emma@support.com',
    fullName: 'Emma Wilson',
    role: 'agent',
    isActive: true,
    createdAt: '2024-02-01T00:00:00Z',
    lastActiveAt: new Date().toISOString(),
  },
];

export const mockCategories: TicketCategory[] = [
  {
    id: 'cat-1',
    name: 'Technical Issue',
    description: 'Technical problems and bugs',
    color: '#EF4444',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'cat-2',
    name: 'Billing',
    description: 'Billing and payment issues',
    color: '#10B981',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'cat-3',
    name: 'Account',
    description: 'Account management and access',
    color: '#3B82F6',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'cat-4',
    name: 'Feature Request',
    description: 'New feature requests',
    color: '#8B5CF6',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'cat-5',
    name: 'General Inquiry',
    description: 'General questions',
    color: '#6B7280',
    createdAt: '2024-01-01T00:00:00Z',
  },
];

export const mockKBArticles: KBArticle[] = [
  {
    id: 'kb-1',
    title: 'How to Reset Your Password',
    content: '# Password Reset Guide\n\n1. Go to the login page\n2. Click "Forgot Password"\n3. Enter your email address\n4. Check your email for reset link\n5. Click the link and create new password',
    summary: 'Step-by-step guide for resetting your password',
    categoryId: 'cat-3',
    tags: ['password', 'account', 'security'],
    viewCount: 145,
    helpfulCount: 132,
    usageCount: 89,
    isPublished: true,
    createdBy: '1',
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: 'kb-2',
    title: 'Common Issues with Password Reset Links',
    content: '# Troubleshooting Reset Links\n\n## Link Expired\nReset links expire after 24 hours. Request a new one.\n\n## Link Not Working\nTry copying the full URL or clearing browser cache.',
    summary: 'Solutions for password reset link problems',
    categoryId: 'cat-1',
    tags: ['password', 'troubleshooting', 'account'],
    viewCount: 98,
    helpfulCount: 85,
    usageCount: 67,
    isPublished: true,
    createdBy: '2',
    createdAt: '2024-01-12T00:00:00Z',
    updatedAt: '2024-01-12T00:00:00Z',
  },
  {
    id: 'kb-3',
    title: 'Understanding Your Billing Cycle',
    content: '# Billing Information\n\nYour billing cycle starts on the day you subscribe and renews monthly.',
    summary: 'Explanation of billing cycles and charges',
    categoryId: 'cat-2',
    tags: ['billing', 'subscription', 'payments'],
    viewCount: 234,
    helpfulCount: 201,
    usageCount: 156,
    isPublished: true,
    createdBy: '1',
    createdAt: '2024-01-08T00:00:00Z',
    updatedAt: '2024-01-08T00:00:00Z',
  },
];

export const mockTickets: Ticket[] = [
  {
    id: 'ticket-1',
    ticketNumber: 'TKT-000001',
    subject: 'Password reset link not working',
    description: 'I requested a password reset but the link in my email is not working. When I click it, I get an error message saying "Invalid or expired token". I tried requesting multiple times but same issue.',
    summary: 'User unable to reset password - link shows invalid token error',
    status: 'in_progress',
    priority: 'high',
    categoryId: 'cat-3',
    assignedTo: '2',
    createdBy: 'customer@example.com',
    createdAt: '2024-10-03T14:30:00Z',
    updatedAt: '2024-10-03T15:00:00Z',
  },
  {
    id: 'ticket-2',
    ticketNumber: 'TKT-000002',
    subject: 'Charged twice for subscription',
    description: 'I was charged twice for my monthly subscription this month. I see two charges of $29.99 on my credit card statement from October 1st.',
    summary: 'Duplicate billing - two charges for single subscription period',
    status: 'open',
    priority: 'urgent',
    categoryId: 'cat-2',
    assignedTo: '3',
    createdBy: 'user123@email.com',
    createdAt: '2024-10-04T09:15:00Z',
    updatedAt: '2024-10-04T09:15:00Z',
  },
  {
    id: 'ticket-3',
    ticketNumber: 'TKT-000003',
    subject: 'Cannot access dashboard',
    description: 'Getting 403 error when trying to access my dashboard.',
    summary: 'Access denied error on dashboard',
    status: 'resolved',
    priority: 'medium',
    categoryId: 'cat-1',
    assignedTo: '2',
    createdBy: 'test@user.com',
    createdAt: '2024-10-02T10:00:00Z',
    updatedAt: '2024-10-03T11:30:00Z',
    resolvedAt: '2024-10-03T11:30:00Z',
  },
];

export const mockClusters: TicketCluster[] = [
  {
    id: 'cluster-1',
    name: 'Password Reset Issues',
    description: 'Multiple users experiencing problems with password reset functionality',
    ticketIds: ['ticket-1'],
    ticketCount: 12,
    firstSeen: '2024-10-01T00:00:00Z',
    lastSeen: new Date().toISOString(),
    isTrending: true,
    createdAt: '2024-10-01T00:00:00Z',
  },
  {
    id: 'cluster-2',
    name: 'Billing Discrepancies',
    description: 'Users reporting unexpected charges or double billing',
    ticketIds: ['ticket-2'],
    ticketCount: 8,
    firstSeen: '2024-10-03T00:00:00Z',
    lastSeen: new Date().toISOString(),
    isTrending: true,
    createdAt: '2024-10-03T00:00:00Z',
  },
];

export const mockAnalytics: AgentAnalytics[] = [
  {
    id: 'analytics-1',
    agentId: '2',
    date: new Date().toISOString().split('T')[0],
    ticketsCreated: 3,
    ticketsResolved: 5,
    avgResponseTimeMinutes: 12.5,
    avgResolutionTimeMinutes: 45.2,
    totalResponses: 15,
    kbArticlesCreated: 1,
  },
  {
    id: 'analytics-2',
    agentId: '3',
    date: new Date().toISOString().split('T')[0],
    ticketsCreated: 2,
    ticketsResolved: 3,
    avgResponseTimeMinutes: 18.3,
    avgResolutionTimeMinutes: 52.7,
    totalResponses: 9,
    kbArticlesCreated: 0,
  },
];
